/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int FUNC = 6;
  /** RegularExpression Id. */
  int ACHAVES = 7;
  /** RegularExpression Id. */
  int FCHAVES = 8;
  /** RegularExpression Id. */
  int APARENTESES = 9;
  /** RegularExpression Id. */
  int FPARENTESES = 10;
  /** RegularExpression Id. */
  int VOID = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int THEN = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int REPEAT = 15;
  /** RegularExpression Id. */
  int RETURN = 16;
  /** RegularExpression Id. */
  int UNTIL = 17;
  /** RegularExpression Id. */
  int OUTPUT = 18;
  /** RegularExpression Id. */
  int NEWVAR = 19;
  /** RegularExpression Id. */
  int OP = 20;
  /** RegularExpression Id. */
  int TIPO = 21;
  /** RegularExpression Id. */
  int TRUE = 22;
  /** RegularExpression Id. */
  int FALSE = 23;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 24;
  /** RegularExpression Id. */
  int VIRGULA = 25;
  /** RegularExpression Id. */
  int IGUAL = 26;
  /** RegularExpression Id. */
  int DIGITO = 27;
  /** RegularExpression Id. */
  int NUMLIT = 28;
  /** RegularExpression Id. */
  int ID = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"func\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"void\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"repeat\"",
    "\"return\"",
    "\"until\"",
    "\"System.output\"",
    "\"newVar\"",
    "<OP>",
    "<TIPO>",
    "\"true\"",
    "\"false\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "<DIGITO>",
    "<NUMLIT>",
    "<ID>",
  };

}
